server:
  port: 7005
spring:
  application:
    name: C-SERVER
eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka