server:
  port: 7003
spring:
  application:
    name: B-SERVER
eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/