server:
  port: 7009
spring:
  application:
    name: zuul-server
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/zuul?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
zuul:
  prefix: /youyuan
  ignored-services: "*"
  retryable: true
  routes:
#    ATEST:
#      serviceId: A-SERVER
#      path: /a/**
#    BTEST:
#      serviceId: B-SERVER
#      path: /b/**
#    CTEST:
#      serviceId: C-SERVER
#      path: /c/**
    DTEST:
      serviceId: D-SERVER
      path: /d/**

