server:
  port: 7009
spring:
  application:
    name: zuul-server
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/zuul?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
zuul:
  prefix: /youyuan
  ignored-services: "*"
  retryable: true
  routes:
#    ATEST:
#      serviceId: A-SERVER
#      path: /a/**
#    BTEST:
#      serviceId: B-SERVER
#      path: /b/**
#    CTEST:
#      serviceId: C-SERVER
#      path: /c/**
    DTEST:
      serviceId: D-SERVER
      path: /d/**
  ribbon:
    eager-load:
      enabled: true   #开启ribbon组件的饥饿加载，使微服务在启动的时候就初始化ribbon组件，避免第一次请求初始化造成的请求超时的问题
    ConnectTimeout: 3000              #请求连接的超时时间
    ReadTimeout: 3000                 #请求处理的超时时间
    OkToRetryOnAllOperations: true    #对所有的操作请求都进行重试，如果是get则可以，如果是post,put等操作没有实现幂等的情况下是很危险的
    MaxAutoRetries: 1                 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
    MaxAutoRetriesNextServer: 1       #切换实例的重试次数

